# run: conda env create -- file environment.yml
# activate: source activate MassResponseToTemp
name: MassResponseToTemp
dependencies: 
- python=2.7.10
- gdal=2.0.0
- pip=8.1.2
- pip: 
    - retriever=2.0.0
    - matplotlib=1.4.3
    - pandas=0.16.2
    - numpy=1.9.2
    - statsmodels=0.6.1
    - joblib=0.9.4
